---
title: "Business Intelligence Lab 4"
author: "Chicken-nuggets"
date: "15th october 2023"
output:
  github_document: 
    toc: yes
    toc_depth: 4
    fig_width: 6
    fig_height: 4
    df_print: default
editor_options:
  chunk_output_type: console
---

# Student Details

+--------------------------------+-------------------------------+
| **Student ID Number and Name** | 1.  137118 Fatoumata Camara   |
|                                | 2.  127039 Ayan Ahmed         |
|                                | 3.  136869 Birkanwal Bhambra  |
|                                | 4.  127602 Trevor Anjere      |
|                                | 5.  133824 Habiba Siba        |
+--------------------------------+-------------------------------+
| **BBIT 4.2 Group**             | Chicken-nuggets               |
+--------------------------------+-------------------------------+

```{r Required Packages}
if (require("readr")) {
  require("readr")
} else {
  install.packages("readr", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}


if (require("caret")) {
  require("caret")
} else {
  install.packages("caret", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

if (require("e1071")) {
  require("e1071")
} else {
  install.packages("e1071", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

if (require("factoextra")) {
  require("factoextra")
} else {
  install.packages("factoextra", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

if (require("FactoMineR")) {
  require("FactoMineR")
} else {
  install.packages("FactoMineR", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

```

```{r Loading the Student performance Dataset}
library(readr)
StudentPerformanceDataset <- read_csv("data/StudentPerformanceDataset.csv")
View(StudentPerformanceDataset)
```

```{r Scale Data Transform}
##visualization using histogram----
#Histogram before transformation
summary(StudentPerformanceDataset)
hist(StudentPerformanceDataset$YOB, main = "Bar Plot of gender",
     xlab = "YOB", ylab = "Frequency", col = "purple")

hist(StudentPerformanceDataset$anticipate_test_questions, main = "Bar Plot of Anticipate test questions",
     xlab = "Anticipate test Questions", ylab = "Frequency", col = "blue")

hist(StudentPerformanceDataset$gender, main = "Bar Plot of YOB",
     xlab = "Gender", ylab = "Frequency", col = "yellow")

hist(StudentPerformanceDataset$A1, main = "Bar Plot of enjoyin the Unit",
     xlab = "Bar Plot of enjoying the Unit", ylab = "Frequency", col = "blue")


hist(StudentPerformanceDataset$Average_Rating, main = "Average_Rating",
     xlab = "Average_Rating", ylab = "Frequency", col = "pink")


hist(StudentPerformanceDataset$Quizzes, main = "Bar Plot of Quizzes",
     xlab = "Quizzes", ylab = "Frequency", col = "blue")


hist(StudentPerformanceDataset$LabWork, main = "Bar Plot of LabWork",
     xlab = "LabWork ", ylab = "Frequency", col = "pink")


hist(StudentPerformanceDataset$CAT1, main = "Bar Plot of CAT1",
     xlab = "CAT1", ylab = "Frequency", col = "blue")

hist(StudentPerformanceDataset$CAT2, main = "Bar Plot of CAT 2",
     xlab = "CAT2", ylab = "Frequency", col = "purple")

hist(StudentPerformanceDataset$Coursework, main = "Bar Plot of Coursework",
     xlab = "Coursework", ylab = "Frequency", col = "pink")

hist(StudentPerformanceDataset$EXAM, main = "Bar Plot of EXAM",
     xlab = "EXAM", ylab = "Frequency", col = "blue")

hist(StudentPerformanceDataset$TOTAL, main = "Bar Plot of TOTAL Semester marks",
     xlab = "TOTAL Semester marks", ylab = "Frequency", col = "red")


# transformation
model_of_the_transform <- preProcess(StudentPerformanceDataset, method = c("scale"))
print(model_of_the_transform)
StudentPerformanceDataset_scale_transform <- predict(model_of_the_transform,
                                             StudentPerformanceDataset)

#Histogram after transformation
summary(StudentPerformanceDataset_scale_transform)

hist(StudentPerformanceDataset_scale_transform$YOB, main = "Bar Plot of gender",
     xlab = "YOB", ylab = "Frequency", col = "purple")

hist(StudentPerformanceDataset_scale_transform$anticipate_test_questions, main = "Bar Plot of Anticipate test questions",
     xlab = "Anticipate test Questions", ylab = "Frequency", col = "blue")

hist(StudentPerformanceDataset_scale_transform$gender, main = "Bar Plot of YOB",
     xlab = "Gender", ylab = "Frequency", col = "yellow")

hist(StudentPerformanceDataset_scale_transform$A1, main = "Bar Plot of enjoyin the Unit",
     xlab = "Bar Plot of enjoying the Unit", ylab = "Frequency", col = "blue")


hist(StudentPerformanceDataset_scale_transform$Average_Rating, main = "Average_Rating",
     xlab = "Average_Rating", ylab = "Frequency", col = "pink")


hist(StudentPerformanceDataset_scale_transform$Quizzes, main = "Bar Plot of Quizzes",
     xlab = "Quizzes", ylab = "Frequency", col = "blue")


hist(StudentPerformanceDataset_scale_transform$LabWork, main = "Bar Plot of LabWork",
     xlab = "LabWork ", ylab = "Frequency", col = "pink")


hist(StudentPerformanceDataset_scale_transform$CAT1, main = "Bar Plot of CAT1",
     xlab = "CAT1", ylab = "Frequency", col = "blue")

hist(StudentPerformanceDataset_scale_transform$CAT2, main = "Bar Plot of CAT 2",
     xlab = "CAT2", ylab = "Frequency", col = "purple")

hist(StudentPerformanceDataset_scale_transform$Coursework, main = "Bar Plot of Coursework",
     xlab = "Coursework", ylab = "Frequency", col = "pink")

hist(StudentPerformanceDataset_scale_transform$EXAM, main = "Bar Plot of EXAM",
     xlab = "EXAM", ylab = "Frequency", col = "blue")

hist(StudentPerformanceDataset_scale_transform$TOTAL, main = "Bar Plot of TOTAL Semester marks",
     xlab = "TOTAL Semester marks", ylab = "Frequency", col = "red")
```

```{r  The Centre Basic Transform}
#visualization using Boxplot
#Boxplot before transformation
summary(StudentPerformanceDataset)
boxplot(StudentPerformanceDataset$YOB, main = "boxplot of gender",
     xlab = "YOB", ylab = "Frequency", col = "purple")

boxplot(StudentPerformanceDataset$anticipate_test_questions, main = "boxplot of Anticipate test questions",
     xlab = "Anticipate test Questions", ylab = "Frequency", col = "blue")

boxplot(StudentPerformanceDataset$gender, main = "boxplot of YOB",
     xlab = "Gender", ylab = "Frequency", col = "yellow")

boxplot(StudentPerformanceDataset$A1, main = "boxplot of enjoyin the Unit",
     xlab = "Boxplot of enjoying the Unit", ylab = "Frequency", col = "blue")


boxplot(StudentPerformanceDataset$Average_Rating, main = "Average_Rating",
     xlab = "Average_Rating", ylab = "Frequency", col = "pink")


boxplot(StudentPerformanceDataset$Quizzes, main = "Boxplot of Quizzes",
     xlab = "Quizzes", ylab = "Frequency", col = "blue")


boxplot(StudentPerformanceDataset$LabWork, main = "Boxplot of LabWork",
     xlab = "LabWork ", ylab = "Frequency", col = "pink")


boxplot(StudentPerformanceDataset$CAT1, main = "Boxplot of CAT1",
     xlab = "CAT1", ylab = "Frequency", col = "blue")

boxplot(StudentPerformanceDataset$CAT2, main = "Boxplot of CAT 2",
     xlab = "CAT2", ylab = "Frequency", col = "purple")

boxplot(StudentPerformanceDataset$Coursework, main = "Boxplot of Coursework",
     xlab = "Coursework", ylab = "Frequency", col = "pink")

boxplot(StudentPerformanceDataset$EXAM, main = "Boxplot of EXAM",
     xlab = "EXAM", ylab = "Frequency", col = "blue")

boxplot(StudentPerformanceDataset$TOTAL, main = "Boxplot of TOTAL Semester marks",
     xlab = "TOTAL Semester marks", ylab = "Frequency", col = "red")


#Transformation
model_of_the_transform <- preProcess(StudentPerformanceDataset, method = c("center"))
print(model_of_the_transform)
StudentPerformanceDataset_center_transform <- predict(model_of_the_transform, # nolint
                                           StudentPerformanceDataset)




#Boxplot after transformation
summary(StudentPerformanceDataset_center_transform)
boxplot(StudentPerformanceDataset_center_transform$YOB, main = "boxplot of gender",
        xlab = "YOB", ylab = "Frequency", col = "purple")

boxplot(StudentPerformanceDataset_center_transform$anticipate_test_questions, main = "boxplot of Anticipate test questions",
        xlab = "Anticipate test Questions", ylab = "Frequency", col = "blue")

boxplot(StudentPerformanceDataset_center_transform$gender, main = "boxplot of YOB",
        xlab = "Gender", ylab = "Frequency", col = "yellow")

boxplot(StudentPerformanceDataset_center_transform$A1, main = "boxplot of enjoyin the Unit",
        xlab = "Boxplot of enjoying the Unit", ylab = "Frequency", col = "blue")


boxplot(StudentPerformanceDataset_center_transform$Average_Rating, main = "Average_Rating",
        xlab = "Average_Rating", ylab = "Frequency", col = "pink")


boxplot(StudentPerformanceDataset_center_transform$Quizzes, main = "Boxplot of Quizzes",
        xlab = "Quizzes", ylab = "Frequency", col = "blue")


boxplot(StudentPerformanceDataset_center_transform$LabWork, main = "Boxplot of LabWork",
        xlab = "LabWork ", ylab = "Frequency", col = "pink")


boxplot(StudentPerformanceDataset_center_transform$CAT1, main = "Boxplot of CAT1",
        xlab = "CAT1", ylab = "Frequency", col = "blue")

boxplot(StudentPerformanceDataset_center_transform$CAT2, main = "Boxplot of CAT 2",
        xlab = "CAT2", ylab = "Frequency", col = "purple")

boxplot(StudentPerformanceDataset_center_transform$Coursework, main = "Boxplot of Coursework",
        xlab = "Coursework", ylab = "Frequency", col = "pink")

boxplot(StudentPerformanceDataset_center_transform$EXAM, main = "Boxplot of EXAM",
        xlab = "EXAM", ylab = "Frequency", col = "blue")

boxplot(StudentPerformanceDataset_center_transform$TOTAL, main = "Boxplot of TOTAL Semester marks",
        xlab = "TOTAL Semester marks", ylab = "Frequency", col = "red")

```

```{r Standardize Data Transform}
#ensures that each numeric attribute has a mean value of 0 and a standard deviation of 1
summary(StudentPerformanceDataset)
sapply(StudentPerformanceDataset[ ,-1 ], sd)

model_of_the_transform <- preProcess(StudentPerformanceDataset,
                                     method = c("scale", "center"))
print(model_of_the_transform)
StudentPerformanceDataset_standardize_transform <- predict(model_of_the_transform, 
                                                           StudentPerformanceDataset)

# AFTER
summary(StudentPerformanceDataset_standardize_transform)
sapply(StudentPerformanceDataset_standardize_transform[, -1], sd)


```

```{r Normalizing Data Transform}
summary(StudentPerformanceDataset)
model_of_the_transform <- preProcess(StudentPerformanceDataset, method = c("range"))
print(model_of_the_transform)
StudentPerformanceDataset_normalize_transform <- predict(model_of_the_transform, 
                                                         StudentPerformanceDataset)
summary(StudentPerformanceDataset_normalize_transform)

```


```{r Applying a Yeo-Johnson Power Transform}
summary(StudentPerformanceDataset)

#Calculating the skewness before 
sapply(StudentPerformanceDataset[, -1],  skewness, type = 2)

# histogram to view the skewness before the Box-Cox transform

hist(StudentPerformanceDataset$YOB, main = "Bar Plot of gender",
     xlab = "YOB", ylab = "Frequency", col = "purple")

hist(StudentPerformanceDataset$anticipate_test_questions, main = "Bar Plot of Anticipate test questions",
     xlab = "Anticipate test Questions", ylab = "Frequency", col = "blue")

hist(StudentPerformanceDataset$gender, main = "Bar Plot of YOB",
     xlab = "Gender", ylab = "Frequency", col = "yellow")

hist(StudentPerformanceDataset$A1, main = "Bar Plot of enjoyin the Unit",
     xlab = "Bar Plot of enjoying the Unit", ylab = "Frequency", col = "blue")


hist(StudentPerformanceDataset$Average_Rating, main = "Average_Rating",
     xlab = "Average_Rating", ylab = "Frequency", col = "pink")


hist(StudentPerformanceDataset$Quizzes, main = "Bar Plot of Quizzes",
     xlab = "Quizzes", ylab = "Frequency", col = "blue")


hist(StudentPerformanceDataset$LabWork, main = "Bar Plot of LabWork",
     xlab = "LabWork ", ylab = "Frequency", col = "pink")


hist(StudentPerformanceDataset$CAT1, main = "Bar Plot of CAT1",
     xlab = "CAT1", ylab = "Frequency", col = "blue")

hist(StudentPerformanceDataset$CAT2, main = "Bar Plot of CAT 2",
     xlab = "CAT2", ylab = "Frequency", col = "purple")

hist(StudentPerformanceDataset$Coursework, main = "Bar Plot of Coursework",
     xlab = "Coursework", ylab = "Frequency", col = "pink")

hist(StudentPerformanceDataset$EXAM, main = "Bar Plot of EXAM",
     xlab = "EXAM", ylab = "Frequency", col = "blue")

hist(StudentPerformanceDataset$TOTAL, main = "Bar Plot of TOTAL Semester marks",
     xlab = "TOTAL Semester marks", ylab = "Frequency", col = "red")

# Transformation
model_of_the_transform <- preProcess(StudentPerformanceDataset, method = c("YeoJohnson"))
print(model_of_the_transform)
StudentPerformanceDataset_yeo_johnson_transform <- predict(model_of_the_transform,StudentPerformanceDataset)

# AFTER
summary(StudentPerformanceDataset_yeo_johnson_transform)

sapply(StudentPerformanceDataset_yeo_johnson_transform[, -1],  skewness, type = 2)



hist(StudentPerformanceDataset_yeo_johnson_transform$YOB, main = "Bar Plot of gender",
     xlab = "YOB", ylab = "Frequency", col = "purple")

hist(StudentPerformanceDataset_yeo_johnson_transform$anticipate_test_questions, main = "Bar Plot of Anticipate test questions",
     xlab = "Anticipate test Questions", ylab = "Frequency", col = "blue")

hist(StudentPerformanceDataset_yeo_johnson_transform$gender, main = "Bar Plot of YOB",
     xlab = "Gender", ylab = "Frequency", col = "yellow")

hist(StudentPerformanceDataset_yeo_johnson_transform$A1, main = "Bar Plot of enjoyin the Unit",
     xlab = "Bar Plot of enjoying the Unit", ylab = "Frequency", col = "blue")


hist(StudentPerformanceDataset_yeo_johnson_transform$Average_Rating, main = "Average_Rating",
     xlab = "Average_Rating", ylab = "Frequency", col = "pink")


hist(StudentPerformanceDataset_yeo_johnson_transform$Quizzes, main = "Bar Plot of Quizzes",
     xlab = "Quizzes", ylab = "Frequency", col = "blue")


hist(StudentPerformanceDataset_yeo_johnson_transform$LabWork, main = "Bar Plot of LabWork",
     xlab = "LabWork ", ylab = "Frequency", col = "pink")


hist(StudentPerformanceDataset_yeo_johnson_transform$CAT1, main = "Bar Plot of CAT1",
     xlab = "CAT1", ylab = "Frequency", col = "blue")

hist(StudentPerformanceDataset_yeo_johnson_transform$CAT2, main = "Bar Plot of CAT 2",
     xlab = "CAT2", ylab = "Frequency", col = "purple")

hist(StudentPerformanceDataset_yeo_johnson_transform$Coursework, main = "Bar Plot of Coursework",
     xlab = "Coursework", ylab = "Frequency", col = "pink")

hist(StudentPerformanceDataset_yeo_johnson_transform$EXAM, main = "Bar Plot of EXAM",
     xlab = "EXAM", ylab = "Frequency", col = "blue")

hist(StudentPerformanceDataset_yeo_johnson_transform$TOTAL, main = "Bar Plot of TOTAL Semester marks",
     xlab = "TOTAL Semester marks", ylab = "Frequency", col = "red")

```



```{r performing (PCA) Linear Algebra Transform}
summary(StudentPerformanceDataset)

model_of_the_transform <- preProcess(StudentPerformanceDataset, method =
                                       c("scale", "center", "pca"))

print(model_of_the_transform)
StudentPerformanceDataset_pca_dr <- predict(model_of_the_transform, StudentPerformanceDataset)
summary(StudentPerformanceDataset_pca_dr)
```


```{r Performing PCA Linear Algebra Transform for Feature Extraction and visualizing }

StudentPerformanceDataset_pca_fe <- princomp(cor(StudentPerformanceDataset[, -1]))
summary(StudentPerformanceDataset_pca_fe)


## Scree Plot ----

factoextra::fviz_eig(StudentPerformanceDataset_pca_fe, addlabels = TRUE)

## Loading Values
StudentPerformanceDataset_pca_fe$loadings[, 1:2]

factoextra::fviz_cos2(StudentPerformanceDataset_pca_fe, choice = "var", axes = 1:2)

factoextra::fviz_pca_var(StudentPerformanceDataset_pca_fe, col.var = "cos2",
                         gradient.cols = c("purple", "red", "yellow"),
                         repel = TRUE)



```



```{r Performing ICA Linear Algebra Transform for Dimensionality Reduction}

if (!is.element("fastICA", installed.packages()[, 1])) {
  install.packages("fastICA", dependencies = TRUE)
}
require("fastICA")
summary(StudentPerformanceDataset)

model_of_the_transform <- preProcess(StudentPerformanceDataset,
                                     method = c("scale", "center", "ica"),
                                     n.comp = 8)
print(model_of_the_transform)
StudentPerformanceDataset_ica_dr <- predict(model_of_the_transform, StudentPerformanceDataset)

summary(StudentPerformanceDataset_ica_dr)

```

